server:
  port: 8090
  servlet:
    context-path: /tcc-java
  error:
    include-message: always
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
spring:
  jpa:
    generate-ddl: true
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/rede-social?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
api:
  security:
    token:
      secret: mockSecret